FROM node:18-alpine AS build
WORKDIR /app

# install deps
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci --silent

# build
COPY frontend/ .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
